# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_plugin 'vagrant-notify'
Vagrant.require_plugin 'vagrant-lxc'

Vagrant.configure("2") do |config|
  config.vm.box = "base"
  config.vm.box = "quantal64"

  config.vm.define :vm1
  config.vm.define :vm2
end
