#!/usr/bin/env ruby

require 'rubygems'
require 'socket'
require 'optparse'

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: example.rb [options]"

  opts.on('-u', '--urgency LEVEL')           { |v| options[:u] = v }
  opts.on('-t', '--expire-time TIME')        { |v| options[:t] = v }
  opts.on('-a', '--app-name APP_NAME')       { |v| options[:a] = v }
  opts.on('-i', '--icon ICON[,ICON...]')     { |v| options[:i] = v }
  opts.on('-c', '--category TYPE[,TYPE...]') { |v| options[:c] = v }
  opts.on('-h', '--hint TYPE:NAME:VALUE')    { |v| options[:h] = v }
  opts.on('-v', '--version')                 { |v| options[:v] = v }

end.parse!

cmd = options.map do |key, value|
  "-#{key} '#{value}'"
end.join(' ')

# TODO: Should escape values
unless ARGV.empty?
  cmd << ' -- '
  cmd << ARGV.map{|a| "'#{a}'"}.join(' ')
end

TCPSocket.open "127.0.0.1", 8081 do |s|
  s.send cmd, 0
end
